table moedas
	lineageTag: c6a7e33b-af51-4c92-9ec0-45efd13f4722

	column Moeda
		dataType: string
		lineageTag: e6726951-be04-4711-8859-c187d88a50aa
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 535f138b-4291-429d-b1e0-ac70f4e41cf0
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		lineageTag: 611a308a-3b6a-48df-ac18-4ec12ab20377
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition moedas = m
		mode: import
		queryGroup: Dimensões
		source = ```
				let
				    source = Table.FromRows(
				        {
				            {"BRL", "Real brasileiro", "R$ #,##0.00;R$ #,##0.00;-"},
				            {"AUD", "Dólar australiano", "$ #,##0.00;$ #,##0.00;-"},
				            {"CAD", "Dólar canadense", "$ #,##0.00;$ #,##0.00;-"},
				            {"CHF", "Franco suíço", "Fr #,##0.00;Fr #,##0.00;-"},
				            {"DKK", "Coroa dinamarquesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"EUR", "Euro", "€ #,##0.00;€ #,##0.00;-"},
				            {"GBP", "Libra Esterlina", "£ #,##0.00;£ #,##0.00;-"},
				            {"JPY", "Iene", "¥ #,##0;¥ #,##0;-"},
				            {"NOK", "Coroa norueguesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"SEK", "Coroa sueca", "kr #,##0.00;kr #,##0.00;-"},
				            {"USD", "Dólar dos Estados Unidos", "$ #,##0.00;$ #,##0.00;-"}
				        },
				        {"Moeda", "Nome", "Formato"}
				    ),
				    
				    changedType = Table.TransformColumnTypes(
				        source,{
				            {"Moeda", type text}, 
				            {"Nome", type text}, 
				            {"Formato", type text}
				        }
				    )
				
				in
				    changedType
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

